name: Golang Build Makefile Github Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: go_build_make${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-go-actions:
    name: Build Go
    runs-on: ubuntu-latest
    permissions:
      contents: write # for checkout
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      # to support custom-gcl golangci-lint module system check https://github.com/golangci/golangci-lint-action/issues/1076
      - name: Run golangci-lint
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
